# Generated by Django 5.2.4 on 2025-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=15)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
